resources:
- name: silk
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/silk
    branch: v1.4.x

jobs:
- name: silk-test-postgres
  plan:
  - aggregate:
    - get: silk
      trigger: true
  - task: test-postgres
    file: silk/ci/test-postgres.yml
    privileged: true

- name: silk-test-mysql
  plan:
  - aggregate:
    - get: silk
      trigger: true
  - task: test-mysql
    file: silk/ci/test-mysql.yml
    privileged: true

- name: silk-test-mysql-5.6
  plan:
  - aggregate:
    - get: silk
      trigger: true
  - task: test-mysql
    file: silk/ci/test-mysql-5.6.yml
    privileged: true
